### ISSUE TITLE
[BUG] WidgetExt::image crashes in 1.0.4

### ISSUE THREAD

**Issue by ThiNei2l** [MoAlyousef/fltk-rs#644]
Hello,
first off I am happy to say that 1.0.4 saved some memory for me.
But now it seems that calling WidgetExt::image on a Widget will crash if said Widget has no image, where it should return None.

The following program will crash:
```rust
use fltk::prelude::{WidgetBase, WidgetExt, GroupExt};

fn main() {
    let app = fltk::app::App::default();
    let mut wind = fltk::window::Window::new(0, 50, 600, 400, "Hello from rust");
    
    let f = fltk::frame::Frame::new(0, 0, 10, 10, "");
    let _test = f.image().is_none();

    wind.end();
    wind.show();

    app.run().unwrap();
}
```

I'm running linux, if that makes a difference.

**Comment by MoAlyousef** [comment]
Yup some missing null checks. Can you try with master:
```toml
[dependencies]
fltk = { version = "1.0.5", git = "https://github.com/moalyousef/fltk-rs" }
```
